language: r

cache:
  - packages
  - ccache

sudo: required
dist: xenial
latex: false

r:
  - release

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

warnings_are_errors: false

env:
   global:
     - _R_CHECK_FORCE_SUGGESTS_=false
     - R_CODECOV=true

r_github_packages:
  - mikejohnson51/AOI
  - jimhester/covr

after_success:
  - if [[ "$\{R_CODECOV\}" ]]; then travis_wait 20 R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
